MoveBike-App/backend-movebike

- src/models/company.model.js
- src/models/costumer.model.js
- src/models/motos.model.js
- src/models/reserve.model.js
I changed little details from models and language. 
1.  `src/models/company.model.js`
2. `src/models/reserve.model.js`
3. `src/models/moto.model.js`
4. `src/models/costumer.model.js`
1. Please review my code syntaxis 
Example of changes made
> [UPDATE]: Models homologation 

- src/libs/bcrypt.js
- src/middlewares/auth.js
- src/middlewares/handleError.js
- src/models/company.model.js
- src/models/costumers.model.js
- src/models/reserves.model.js
- src/routers/company.router.js
- src/routers/costumers.router.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/server.js
- src/usesCases/company.use.js
- src/usesCases/costumers.use.js
- src/usesCases/motos.use.js
- src/usesCases/reserves.use.js
- I implemented the  endpoints for each routers, with your method get, post, delete, patch
- Add middlewares for auth
​
​
> [Taks_name](https://app.asana.com/0/1202873144426895/1203219417953065/f)
​
1. `src/libs/bcrypt.js`
2. `src/middlewares/auth.js`
3. `src/middlewares/handleError.js`
4. `src/routers/company.router.js`
5. `src/routers/costumers.router.js`
6. `src/routers/motos.router.js`
7. `src/routers/reserves.router.js`
​
​
> [FEATURE]: add motos, companies, costumers and reserves routers

- index.js
- src/middlewares/ownerAccount.js
- src/routers/companies.router.js
- src/routers/customers.router.js
- src/routers/reserves.router.js
- src/useCases/costumers.use.js
- src/useCases/customers.use.js
I made the middleware so that the user can edit his own account only.
1.  `/src/middlewares/ownerAccount.js`
​
1. Please review my correct implementation of the middleware in the routes
> [FEATURES]: Owner account middleware

- src/libs/sendgrid.js
- src/middlewares/auth.js
- src/middlewares/authRole.js
- src/middlewares/ownerAccount.js
- src/models/customers.model.js
- src/routers/auth.router.js
- src/routers/companies.router.js
- src/routers/customers.router.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/useCases/auth.use.js
- src/useCases/customers.use.js
- src/useCases/motos.use.js
- src/useCases/reserves.use.js
I changed the references on useCases so frontend can receive the correct information.
> [UPDATE]: Sending required info to frontend

- src/server.js
> [FIX] add cors for browsers

- src/routers/auth.router.js
- src/routers/motos.router.js
- src/useCases/auth.use.js
I just fixed the way i was sending the login info, cause i was having a problem in auth middleware.
Here is the correction when a user logged
> [FIX]a: Auth endpoint

- src/models/features.model.js
- src/models/motos.model.js
- src/routers/features.router.js
- src/server.js
- src/useCases/auth.use.js
- src/useCases/features.use.js
I made features crud and update insomnia
1.  `/src/models/features.model.js`
2.  `/src/routers/features.js`
3.  `/src/useCases/features.use.js`
4.  `/server.js`
​
1. I did not add a reference for the feature as you told me that the task is going to be impemented in front ;)
2. Let me know if theres an error 
GET
POST
> [FEATURE]: Adding features crud

- src/middlewares/ownerAccount.js
- src/routers/reserves.router.js
I created a new middleware for edit and delete reserves.
> [FIX]: Owner account middleware for reserves

- package-lock.json
- package.json
- src/libs/s3/config.js
- src/libs/s3/index.js
- src/middlewares/multer.js
- src/models/customers.model.js
- src/models/motos.model.js
- src/routers/customers.router.js
- src/routers/motos.router.js
- src/useCases/customers.use.js
- src/useCases/motos.use.js
I added a multer middleware for uploading images for customers (avatar & identify) and motos
1.  `/src/middlewares/multer.js`
2.  `/src/models/customers.model.js`
3.  `/src/models/motos.model.js`
4.  `/src/routers/customers.router.js`
5.  `/src/routers/motos.router.js`
6.  `/src/useCases/customers.use.router.js`
7.  `/src/useCases/motos.use.router.js`
​
1-. Please review if this doesnt break implented in frontend ;)
Customers
Motos
> [FEATURES]: Adding images for customers and motos

- src/models/routes.model.js
- src/routers/routes.router.js
- src/server.js
- src/useCases/routes.use.js
I added tourism sites CRUD
1.  `/src/models/routes.model.js`
2.  `/src/routers/routes.router.js`
3.  `/src/useCases/routes.use.js`
4.  `/server.js`
​
Please check i have an error i'm super sleepy :(
> [FEATURE]: Adding tourism sites CRUD

- src/middlewares/auth.js
- src/routers/customers.router.js
- src/routers/motos.router.js
- src/useCases/customers.use.js
- src/useCases/motos.use.js
I modified use cases for editing(update function) images in motos and customers models
##Customer
##Moto
> [UPDATE]: Adding edit customer and moto with multer middleware logic

- src/libs/sendgrid.js
- src/routers/auth.router.js
- src/useCases/auth.use.js
- src/useCases/customers.use.js
- src/useCases/motos.use.js
I made an endpoint for email confirmation, when a user create an account.
1.  `/src/libs./sendgrid.js`
2.  `/src/routers/auth.router.js`
3. `/src/usesCases/auth.useCases/.js`
​
Please review if you need something extra for your logic on frontend;)
> [UPDATE]: Email confirmation

- src/routers/features.router.js
- src/routers/home.router.js
- src/server.js
- src/useCases/features.use.js
I fixed the patch method of features
1.  `/src/routers/features.router.js`
​
Please review that the icons features are visible on frontend!
> [FIX]: Edit features

- src/useCases/motos.use.js
> [UPDATE]: Adding keyIcon reference

- package-lock.json
- package.json
- src/models/company.model.js
- src/models/customers.model.js
- src/models/features.model.js
- src/models/motos.model.js
- src/models/reserves.model.js
- src/models/routes.model.js
- src/routers/companies.router.js
- src/routers/customers.router.js
- src/routers/features.router.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/routers/routes.router.js
- src/useCases/companies.use.js
- src/useCases/customers.use.js
- src/useCases/features.use.js
- src/useCases/motos.use.js
- src/useCases/reserves.use.js
- src/useCases/routes.use.js
I added slugs for every model and change getById to GetBySlug to have a better looking url.
1.  `/src/models`
2.  `/src/routes`
3. `/src/useCases`
​
1-. Please review if my slug implementation is functional for frontend
> [FEATURE]: Adding slugs to models

- src/libs/sendgrid.js
- src/models/reserves.model.js
- src/routers/reserves.router.js
- src/useCases/reserves.use.js
I added a small function for getting a reserve number for each reserve
1.  `/src/useCases/reserves.use.js`
2.  `/src/routers/reserve,router.js`
​
I used a math.random, but i saw that i have to wait almost 8 seconds to create a new reserve, if you think in another way let me know ;)
> [UPDATE]: Adding reserve number logic

- src/middlewares/auth.js
- src/models/costumers.model.js
- src/models/motos.model.js
- src/routers/company.router.js
- src/routers/costumers.router.js
- src/routers/customers.router.js
- src/routers/features.router.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/useCases/costumers.use.js
- src/useCases/customers.use.js
- src/useCases/features.use.js
- src/useCases/motos.use.js
- src/useCases/reserves.use.js
- src/usesCases/auth.use.js
- src/usesCases/company.use.js
- src/usesCases/costumers.use.js
- src/usesCases/motos.use.js
- src/usesCases/reserves.use.js
I just made get by id and get by slug in every route.
> [UPDATE]: Making endpoints corrections

- src/middlewares/auth.js
- src/models/customers.model.js
- src/routers/customers.router.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/useCases/customers.use.js
- src/useCases/reserves.use.js
I added a function to calculate reserves number
1.  `/useCases/reserves.use.js`
2.  `/routers/reserves.router/index.js`
​
1-. Please review if it looks good the way reserve number is showing
> [UPDATE]: Reserve Number

- src/libs/jwt.js
- src/middlewares/auth.js
- src/middlewares/multer.js
- src/routers/motos.router.js
- src/routers/routes.router.js
- src/useCases/customers.use.js
- src/useCases/reserves.use.js
- src/useCases/routes.use.js
I changed the reserve number function por this one.
Result
> [UPDATE]: Updating reserve number

- src/libs/jwt.js
- src/middlewares/auth.js
- src/routers/motos.router.js
- src/useCases/features.use.js
- src/useCases/reserves.use.js
- src/useCases/routes.use.js
> cleaning the code

- src/models/customers.model.js
- src/routers/customers.router.js
- src/routers/reserves.router.js
- src/useCases/auth.use.js
- src/useCases/customers.use.js
Updating model verifications and sending new info to frontend.
##Login response
> [UPDATE]: Updating model

- src/libs/sendgrid.js
- src/models/reserves.model.js
- src/models/routes.model.js
- src/routers/auth.router.js
- src/routers/customers.router.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/useCases/customers.use.js
- src/useCases/motos.use.js
- src/useCases/reserves.use.js
I made a function to consult by id and by slug in the same endpoint.
Use your headers to chose your search type
> [UPDATE]: homologatingId

- src/middlewares/auth.js
- src/models/customers.model.js
- src/routers/auth.router.js
- src/routers/customers.router.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/useCases/auth.use.js
- src/useCases/customers.use.js
I added a validation for account verification.
> [UPDATE]: Adding validation for login

- src/libs/s3/config.js
- src/middlewares/multer.js
I added  validation for files size
1.  `/src/middlewares/multer.js`
​
1. Please review if 1MB is a good size for our app, let me know if you want to send you another thing to frontend!
> [FEATURE]: Adding max size files validation

- src/models/company.model.js
- src/routers/motos.router.js
- src/useCases/motos.use.js
- src/useCases/reserves.use.js
Modifying company model and first part of dates endpoint
> [FEATURES]: add Dates Endpoint

- src/useCases/reserves.use.js
> [UPDATE]: updating sendgrid dynamic templates

- index.js
- src/middlewares/multer.js
- src/models/motos.model.js
- src/models/reserves.model.js
- src/routers/motos.router.js
- src/routers/reserves.router.js
- src/routers/routes.router.js
- src/useCases/reserves.use.js
I implemented the availability moto, in motos model there's a field "notAvailableDates". 
When a reserve is created the array of the reserve dates goes to the moto model.
1.  `/useCases/reserves.use.js`
2.  `/models/reserves.model.js`
3.  `/models/motos.model.js`
​
1. Please review if that everything goues okay in frontend respect the dates format, if something needs to be changed let mi know ;)
> [FEATURE]: Adding motos availability logic

- src/routers/routes.router.js
- src/useCases/routes.use.js
I update get routes by id to improve the url view. with a 'getByType' useCase function.
1.  `/useCases/routes.use.js`
2.  `/routers/routes.router.js`
​
1. Remember you have to add to your fetch headers the typeSearch you want.
> [UPDATE]: Adding get route by slug

- src/routers/reserves.router.js
- src/useCases/reserves.use.js
I made an endpoint for database numbers consulting (top 5 rental, all reserves, canceled reserves)
1.  `/routers/reserves.router.js`
2.  `/useCases/reserves.use.index.js`
​
1. Please review my endpoint implementation, maybe it can be optimized.
I will appreciate your help for the 'actual reserves' logic.
> [FEATURES]: Dashboard analytics

- src/useCases/reserves.use.js
I modified the create reserve logic, i was having troubles on frontend.
1.  `/useCase/reserve.use.js`
​
1. Please review if your are not having problems on frontend when you pay.
> [UPDATE]: Create reserve logic

- src/routers/reserves.router.js
- src/useCases/auth.use.js
- src/useCases/customers.use.js
- src/useCases/features.use.js
- src/useCases/motos.use.js
- src/useCases/reserves.use.js
- src/useCases/routes.use.js
I'm working on how many the company can earn in a range of time. I joined two functions in one endpoint reserves/filter
1.  `/routers/reserves.router.js`
2.  `/useCases/reserves.use.js`
​
1. Please review if it would be necessary to remove amount cards footer
> [UPDATE]: Joining functions for dashboard analytics

- src/models/routes.model.js
I added a new field for the preview to the routes model
1.  `/model/route.model.js`
​
1. Please review if that field its okay for frontend.
> [UPDATE]: Updating routes model

- src/models/reactions.model.js
- src/models/routes.model.js
- src/routers/reactions.router.js
- src/routers/reserves.router.js
- src/server.js
- src/useCases/reactions.use.js
- src/useCases/routes.use.js
I implemented the reactions logic for routes making a new endpoint.
A customer can have a like reactions to them favorites routes.
1.  `/models/reactions.model.js`
2.  `/routers/reactions.router.js`
3.  `/useCase/reactions.use.js`
4.  `server.js`
​
1. Please review my code logic and please have my button heart ready so i can integrate it ;)
> [FEATURES]: Adding reactions logic

- src/routers/reactions.router.js
- src/routers/reserves.router.js
- src/useCases/reactions.use.js
I updated the auth and acces middlewares for get method on the main page.
1.  `/routers/reserves.js`
​
1. Please review if my available-vehicles middleware is functional for you, because of the date format 
Endpoint 
http://localhost:8080/reserves/available-vehicles?initialDate=2022-12-01&finalDate=2022-12-30
> [UPDATE]: Modifying routes middlewares

- src/models/routes.model.js
I added a field to route model for an ubication google maps link.
1.  `/models/route.model.js`
​
1. Let me know if the field requires another validation
> [UPDATE]: route model

- src/libs/jwt.js
- src/routers/reserves.router.js
- src/useCases/customers.use.js
- src/useCases/reserves.use.js
I modifies the token xpirations for 6h verify e-mail and 1 day for login. 
1-. `src/useCase/customers.use.js`
2-. `src/libs/jwt.js`
> [UPDATE]: Token expiration
